### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by bjones1**
Brad,

I spent some time getting the new Flask-based server updated with unit tests, documentation, and some fixes. It now can use a web2py Auth_User table to login users, among other things. Definitely needs more work, though -- this is more a heads-up, then a "work is done".

To do
- More unit tests!
- Get the API /hsblog fully up and running.

### CODE REVIEW

**Comment by bjones1** [comment]
OK, this is good progress for now. The testing framework is set up, I've laid a foundation for good documentation of the code, and the code itself is fairly DRY. To do:

- [ ] Finish out translating `hsblog` and the needed database models it uses.
- [ ] @bnmnetp, identify which endpoints aren't needed. (Do we use `savehilight`/`deletehilight`/`gethilight`? If so, we should instead use Hypothesis -- I use that now, and it's very nice.)
- [ ] Integrate this into the Selenium tests in the Runestone components. Make sure the JS/server interactions produce correct value in the database.

**Comment by bnmnetp** [comment]
Finally, grades are in and I'm taking some time to look at this.

I wish we could find a way to be compatible with the logins from web2py and still be on python3.  I hate having web2py continually dragging us back to python2.

**Comment by bjones1** [comment]
Congratulations on finishing up! Yall's semester ends quite late...I've been on vacation for a week :).

This all runs on Python 3 -- latest dev versions of web2py (at least the gluons stuff I need) works fine.

**Comment by bnmnetp** [comment]
OK, I guess the web2py guys have finally accepted the reality of Python3 😄 

So, I'm looking at the tests, and running them....  I'm seeing an error in test_5 of the API testing.

```
ERROR at teardown of TestRunestoneApi.test_5
...

E       psycopg2.ProgrammingError: relation "model_for_testing" does not exist
E       LINE 1: DELETE FROM model_for_testing
E                           ^
```

I'm assuming this should be defined due to the class ModelForTesting

**Comment by bjones1** [comment]
Hmmm, I can't reproduce this on my PC.  I'm running:

```
E:\Runestone\NewServer>python -m pytest tests
============================= test session starts =============================
platform win32 -- Python 3.6.1, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: E:\Runestone\NewServer, inifile:
collected 14 items

tests\test_all.py ..............

========================== 14 passed in 1.77 seconds ==========================
```

I assume that the model isn't being created? It is defined in `ModelForTesting` inside `test_5`. I'll look when I have a minute...

**Comment by bjones1** [comment]
OK, that should fix it. Would you try?

**Comment by bnmnetp** [comment]
yep, that did it.  Thanks

**Pull request closed without merging**
